version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111           # MySQL root 비밀번호
      MYSQL_DATABASE: test                # 기본 생성할 데이터베이스
    ports:
      - "3306:3306"  # 호스트의 3306 포트를 컨테이너의 3306 포트에 매핑

  redis:
    image: redis:7.0
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"  # 호스트의 6379 포트를 컨테이너의 6379 포트에 매핑